project:
  type: book
  output-dir: _plm

book:
  title: "PhD: People-Like-Me"
  # output-file: "TSA project analysis"
  date: "04/30/2024"
  navbar:
    search: true
    downloads: [pdf, epub]
  repo-url: https://github.com/Goodgolden/tsa
  repo-actions: [edit]
  sidebar:
    search: true
    tools:
      - icon: github
        href: https://github.com/Goodgolden/tsa
        aria-label: GitHub
      - icon: share
        aria-label: Email
      - icon: hospital
        aria-label: CU Anschutz
        href: https://coloradosph.cuanschutz.edu/education/departments/biostatistics-informatics
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - 0_todo.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    code-fold: true
    code-tools: true
    code-link: true
    df-print: paged
    # fig-cap-location: top
    fig.topcaption: TRUE
    author-meta: "Randy Jin, Elizabeth Juarez-Colunga"
    # include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual

toc: true

comments:
  hypothesis: true
